packages:
  - 'apps/*'
  - 'packages/*'
  - 'configs/*'
onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - unrs-resolver
blockExoticSubdeps: true
allowBuilds:
  '@swc/core': true
  esbuild: true
  unrs-resolver: true
